#!/bin/bash
#
# Copyright (C) 2007 Gabriel Falcão <gabrielteratos@gmail.com>
# Copyright (C) 2007 Lincoln de Sousa <lincoln@archlinux-br.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo Usage: $0
    echo Generates a file called messages.pot.
    echo
    echo After run this script, rename the messages.pot file to yourlanguage.po
    echo edit that with your prefered po editor, like poedit or gtranslator.
    echo
    echo After that please send me your work to gabrielteratos@gmail.com
    echo with subject: GUAKE TRANSLATION
    echo Thanks!
    exit 0
fi

find . -name '*.glade' -exec intltool-extract --type="gettext/glade" {} \;
find . -name '*.glade.h' -exec mv {} . \;
find . -name '*.py' -exec xgettext -k_ -kN_ -o messages.pot {} *.h --from-code=utf-8 \;
rm *.h

exit 0
