.TH "guake" "1"
.SH "NAME"
guake \(em A drop-down terminal for GNOME environment.
.SH "SYNOPSIS"
.PP
\fBguake\fR [\fB-h, \-\-help\fR\fP] [\fB-s, --show-hide\fR\fP] [\fB-p, --preferences\fR\fP] [\fB-a, --about\fR\fP] [\fB-q, --quit\fR\fP]
.SH "DESCRIPTION"
.PP
Guake is a drop-down terminal for GNOME and any other desktop.
It aims to provide a quick-access terminal, that show/hide on screen with a simple key pressing.
.PP
.SH "OPTIONS"
.B \-h, \-\-help
Show summary of options.
.TP
.B \-s, \-\-show\-hide
Toggle the visibility of guake
.TP
.B \-p, \-\-preferences
Shows the preferences window of guake
.TP
.B \-a, \-\-about
Shows the about window of guake
.TP
.B \-q, \-\-quit
Closes the current running guake
.SH AUTHOR
guake was written by <gabriel@guake-terminal.org>
.PP
This manual page was written by Gabriel Falcao Goncalves de Moura <gabriel@guake-terminal.org>,
for the Debian project (but may be used by others).
