.TH "guake" "1"
.SH "NAME"
guake \(em A drop-down terminal for GNOME environment.
.SH "SYNOPSIS"
.PP
\fBguake\fR [\fB-h, \-\-help\fR\fP] [\fB-p, \-\-preferences\fR\fP] [\fB-a, \-\-about\fR\fP] [\fB-q, \-\-quit\fR\fP] [\fB-f, \-\-fullscreen\fR\fP] [\fB-t, \-\-toggle\-visiblity\fR\fP] [\fB\-\-show\fR\fP] [\fB\-\-hide\fR\fP] [\fB-s, \-\-select\-tab\fR\fP] [\fB-g, \-\-selected\-tab\fR\fP] [\fB-e, \-\-execute\-command\fR\fP] [\fB-t, \-\-tab\-index\fR\fP] [\fB\-\-bgcolor\fR\fP] [\fB\-\-fgcolor\fR\fP] [\fB-r, \-\-rename-current\-tab\fR\fP]
.SH "DESCRIPTION"
.PP
Guake is a drop-down terminal for GNOME and any other desktop.
It aims to provide a quick-access terminal, that show/hide on screen with a simple key pressing.
.PP
.SH "OPTIONS"
.B \-h, \-\-help
Show summary of options.
.TP
.B \-t, \-\-toggle\-visibility
Toggle the visibility of guake
.TP
.B \-\-show
Display the main window
.TP
.B \-\-hide
Hide the main window
.TP
.B \-p, \-\-preferences
Shows the preferences window of guake
.TP
.B \-a, \-\-about
Shows the about window of guake
.TP
.B \-n, \-\-new\-tab
Create a new tab in Guake
.TP
.B \-s, \-\-select\-tab
Select a tab given its 0-based index
.TP
.B \-g, \-\-selected\-tab
Return the index of the current tab
.TP
.B \-e, \-\-execute\-command
Execute a command in the selected tab
.TP
.B \-i, \-\-tab\-index
Specify which tab to rename. Default is 0.
.TP
.B \-\-bgcolor
Set the hexadecimal (#rrggbb) background color of the selected tab.
.TP
.B \-\-fgcolor
Set the hexadecimal (#rrggbb) foreground color of the selected tab
.TP
.B \-\-rename\-tab
Rename the specified tab. Reset to default if TITLE is a single dash "\-".
.TP
.B \-r, \-\-rename\-current\-tab
Rename the current tab. Reset to default if TITLE is a single dash "\-".
.TP
.B \-q, \-\-quit
Closes the current running guake
.SH AUTHOR
guake was originally written by <gabriel@guake-terminal.org>
.PP
This manual page was written by Gabriel Falcao Goncalves de Moura <gabriel@guake-terminal.org>,
for the Debian project (but may be used by others).
